version: "3.9"
services:
  postgres:
    pull_policy: always
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

# To use this file with the integration tests, see docs/testing.md
