[package]
name = "ioxd_router"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies] # In alphabetical order
async-trait = "0.1"
authz = { path = "../authz" }
clap_blocks = { path = "../clap_blocks" }
data_types = { path = "../data_types" }
gossip = { version = "0.1.0", path = "../gossip" }
gossip_schema = { version = "0.1.0", path = "../gossip_schema" }
hashbrown = { workspace = true }
hyper = "0.14"
iox_catalog = { path = "../iox_catalog" }
ioxd_common = { path = "../ioxd_common" }
metric = { path = "../metric" }
mutable_batch = { path = "../mutable_batch" }
object_store = { workspace = true }
observability_deps = { version = "0.1.0", path = "../observability_deps" }
router = { path = "../router" }
thiserror = "1.0.49"
tokio = { version = "1.32", features = [
    "macros",
    "net",
    "parking_lot",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
tokio-util = { version = "0.7.9" }
trace = { path = "../trace" }
workspace-hack = { version = "0.1", path = "../workspace-hack" }
